timezone: Europe/Berlin
highlighter: pygments
markdown: redcarpet
permalink: /post/:title

redcarpet:
  extensions: [autolink, strikethrough]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]

paginate: 5
paginate_path: '/blog/:num'

excerpt_separator: "\n\n\n"

# own settings
name: phianca
domain: phianca.github.io
url: http://phianca.github.io/
description: Blog cua Chi Chi
copyright: 2015
author: 
    name: Phianca
    github_link: https://github.com/phianca
    twitter_link: 

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: Phianca

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-63740771-1
